name: Publish NuGet Template

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Pack NuGet template
        run: nuget pack CleanArchTemplate.nuspec

      - name: Publish to NuGet
        run: nuget push *.nupkg -src https://api.nuget.org/v3/index.json ${{ secrets.NUGET_API_KEY }}